repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-ast
    exclude: ^{{cookiecutter\.project_name}}
  - id: check-toml
    exclude: ^{{cookiecutter\.project_name}}
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.1
  hooks:
  - id: toml-sort-fix
    exclude: ^{{cookiecutter\.project_name}}
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories, src/]
    exclude: ^{{cookiecutter\.project_name}}
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    exclude: ^{{cookiecutter\.project_name}}
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
- repo: local
  hooks:
  - id: pylint
    name: pylint
    language: system
    entry: pylint
    types: [python]
    exclude: ^{{cookiecutter\.project_name}}
- repo: local
  hooks:
  - id: mypy
    name: mypy
    language: system
    entry: mypy
    args: [--ignore-missing-imports]
    types: [python]
    exclude: ^{{cookiecutter\.project_name}}
