repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-ast
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pappasam/toml-sort
  rev: v0.22.3
  hooks:
  - id: toml-sort-fix
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories, src/]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/docformatter
  rev: v1.5.1
  hooks:
  - id: docformatter
- repo: local
  hooks:
  - id: pylint
    name: PyLint
    entry: pylint
    language: system
    files: \.py$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.0.1
  hooks:
  - id: mypy
    name: mypy-src
    files: src/.*
    additional_dependencies:
    - .
  - id: mypy
    name: mypy-tests
    files: tests/.*
    additional_dependencies:
    - .[test]
